services:
  api_gateway:
    build: ./http-api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./http-api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - ports=3000
    depends_on:
      mysql_db:
        condition: service_healthy
      nats:
        condition: service_started

  users_microservice:
    build: ./users-microservice
    volumes:
      - ./users-microservice/src:/usr/src/app/src
    command: npm run start:dev
    depends_on:
      mysql_db:
        condition: service_healthy
      nats:
        condition: service_started

  payments_microservice:
    build: ./payments-microservice
    volumes:
      - ./payments-microservice/src:/usr/src/app/src
    command: npm run start:dev
    depends_on:
      mysql_db:
        condition: service_healthy
      nats:
        condition: service_started

  nats:
    image: nats
    ports:
      - 4222:4222

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootAccess
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "user",
          "-ppassword",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
